// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHUGcuZjaRTmIfBXTY1M0L6167_077nk',
    appId: '1:803488921135:web:37bef956e94f23cac2f8da',
    messagingSenderId: '803488921135',
    projectId: 'visitor-d5ed4',
    authDomain: 'visitor-d5ed4.firebaseapp.com',
    storageBucket: 'visitor-d5ed4.firebasestorage.app',
    measurementId: 'G-N6T5WGNCL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5stEFCqj1Rxff29P3r6bAyM4seETeEE',
    appId: '1:803488921135:android:b802c112f069caf7c2f8da',
    messagingSenderId: '803488921135',
    projectId: 'visitor-d5ed4',
    storageBucket: 'visitor-d5ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylZOKcDhm6RSEYIGio42ID-kzbuoRP2M',
    appId: '1:803488921135:ios:bf3c91ad2eb77f7ec2f8da',
    messagingSenderId: '803488921135',
    projectId: 'visitor-d5ed4',
    storageBucket: 'visitor-d5ed4.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagement',
  );

}